- name: Configure BGP Unnumbered Switches
  hosts: all
  become: yes
  gather_facts: yes
  tasks:

  - name: Initial Switch setup
    nclu:
      commit: true
      description: "Initial Management VRF setup"
      commands:
        - add interface eth0 vrf mgmt
        - add hostname "{{ inventory_hostname }}"
        - add interface {{ node[inventory_hostname].ports }}

  - name: Deploy BGP Unnumbered configuration
    nclu:
        commit: true
        description: "Deploy BGP Unnumbered configuration"
        commands:
            - add loopback lo ip address {{ node[inventory_hostname].routing.lo }}
            - add bgp autonomous-system {{ node[inventory_hostname].routing.bgp.asn }}
            - add bgp neighbor {{ node[inventory_hostname].routing.bgp.underlay.external.peers }} remote-as external
            - add bgp redistribute connected
            - add bgp bestpath as-path multipath-relax

#  - name: Deploy BGP Unnumbered Interfaces
#    nclu:
#        commit: true
#        description: "Deploy BGP Unnumbered Interfaces"
#        template: |
#           add bgp neighbor {{ item }} remote-as external
#    with_items:
#      - "{{ node[inventory_hostname].routing.bgp.underlay.external.peers }}"
#    when: node[inventory_hostname].routing.bgp.underlay.external.peers is defined

  - name: Reload Interfaces
    command: ifreload -a
